#!/bin/bash
#
# Project: PlatformChecker
# Author: Mark Battistella
# Website: https://markbattistella.com
#
# Blocking guard on every commit message. Unlike pre-commit, which is advisory
# and always exits 0, this hook refuses the commit.
#
# It enforces the two rules an agent must not be trusted to self-police:
#   1. Mark Battistella is the sole author. No agent or tool attribution.
#   2. The subject is the date, yyyy-mm-dd, and nothing else.
#
# Install by symlinking or calling this from .git/hooks/commit-msg.local, which the
# global ~/.git-hooks/commit-msg dispatcher runs.
#

set -uo pipefail

msg_file="$1"
fail=0

err() { printf '\n[commit-msg] %s\n' "$*" >&2; fail=1; }

# Everything except comment lines and the diff git appends under --verbose.
body="$(sed -e '/^#/d' -e '/^diff --git /,$d' "$msg_file")"
subject="$(printf '%s\n' "$body" | sed -e '/^[[:space:]]*$/d' -e 'q')"

# Merges, reverts and autosquash markers are generated by git or are amend
# plumbing. Leave their format alone, but still check attribution below.
skip_subject=0
case "$subject" in
  "Merge "*|"Revert "*|"fixup! "*|"squash! "*|"amend! "*) skip_subject=1 ;;
esac

# MARK: - Authorship

author_name="$(git var GIT_AUTHOR_IDENT | sed -e 's/ <.*//')"
author_email="$(git var GIT_AUTHOR_IDENT | sed -e 's/.*<//' -e 's/>.*//')"

if [ "$author_name" != "Mark Battistella" ]; then
  err "Author name is '$author_name'. Every commit is authored by Mark Battistella."
fi

case "$author_email" in
  mark_battistella+*@hotmail.com|*@markbattistella.com) ;;
  *) err "Author email '$author_email' is not one of Mark's. Check git config user.email." ;;
esac

# MARK: - Attribution trailers

if printf '%s\n' "$body" | grep -qiE '^[[:space:]]*(co-authored-by|co-committed-by|assisted-by|generated-by|authored-by|on-behalf-of)[[:space:]]*:'; then
  err "Attribution trailer found. Remove it - Mark is the sole author."
  printf '%s\n' "$body" | grep -inE '^[[:space:]]*(co-authored-by|co-committed-by|assisted-by|generated-by|authored-by|on-behalf-of)[[:space:]]*:' >&2
fi

if printf '%s\n' "$body" | grep -q '🤖'; then
  err "Robot emoji found. Remove it."
fi

# Tool and model names, but only where they read as a credit, so an ordinary
# message mentioning a feature name is not caught.
credit='(with|by|via|using|thanks to|help from|assisted by|generated (with|by))'
tools='(claude|anthropic|opus|sonnet|haiku|fable|copilot|cursor|chatgpt|gpt-[0-9]|codex|gemini|llama|devin|windsurf|aider|codebuff|cline)'

if printf '%s\n' "$body" | grep -qiE "${credit}[[:space:]]+[^[:alnum:]]*${tools}"; then
  err "Reads as a credit to a tool or model. Remove it."
  printf '%s\n' "$body" | grep -inE "${credit}[[:space:]]+[^[:alnum:]]*${tools}" >&2
fi

# MARK: - Subject format

if [ "$skip_subject" -eq 0 ]; then
  if ! printf '%s' "$subject" | grep -qE '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'; then
    err "Subject must be the date and nothing else, as yyyy-mm-dd. Got: '$subject'"
  elif [ "$subject" != "$(date +%Y-%m-%d)" ]; then
    printf '\n[commit-msg] Note: subject is %s, today is %s.\n' \
      "$subject" "$(date +%Y-%m-%d)" >&2
  fi

  # A second line, if there is one, must be blank.
  second="$(printf '%s\n' "$body" | sed -n '2p')"
  if [ -n "$second" ]; then
    err "Leave a blank line between the subject and the body."
  fi
fi

if [ "$fail" -ne 0 ]; then
  cat >&2 <<'MSG'

[commit-msg] Commit refused.

A valid message:

    2026-09-22

    - Added the iPhone Duo device check

MSG
  exit 1
fi

exit 0
